openapi: 3.0.4
info:
  title: OpenAPI Example
  version: 1.0.0
  description: An example OpenAPI specification

paths:
  /categories:
    get:
      tags:
        - Categories
      operationId: getCategories
      responses:
        200:
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      tags:
        - Categories
      operationId: createCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        201:
          $ref: '#/components/responses/201'
  /categories/{categoryId}:
    parameters:
      - name: categoryId
        in: path
        required: true
        schema:
          type: number
    put:
      tags:
        - Categories
      operationId: updateCategory
      requestBody:
        description: Update a category
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        200:
          description: Category updated successfully
    delete:
      operationId: deleteCategory
      responses:
        200:
          description: Category deleted successfully
    get:
      operationId: getCategoryById
      responses:
        200:
          description: Category details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
components:
  schemas:
    Category:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        picture:
          type: string
  responses:
    201:
      description: Category created successfully
      headers:
        Location:
          description: The URL of the created resource
          schema:
            type: string
