quarkus:
  datasource:
    db-kind: postgresql
    username: bob
    password: bob
    reactive:
      url: postgresql://localhost:5432/smartbarbo
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
