
POST {{host}}:{{port}}/tables
Content-Type: application/json

{
"name": "characato11",
  "seatCount": 30,
  "active": false


}

###
GET {{host}}:{{port}}/tables
Content-Type: application/json

###

GET {{host}}:{{port}}/tables/{{tableId}}
Content-Type: application/json
###
PUT {{host}}:{{port}}/tables/{{tableId}}
Content-Type: application/json

{
  "name": "characato modificado",
  "seatCount": 40,
  "active": false
}